name: pg
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - pgcore >= 1.4.0
  - matplotlib
  - jupyter
  - pytest
  - numpy
  - scipy<1.12
  - pyvista[all,trame]>=0.42
  - meshio
  - tetgen
  - scooby
